/**
 * generated by Xtext 2.14.0
 */
package ac.soton.xumlb.ui.contentassist;

import ac.soton.xumlb.ui.contentassist.AbstractStatemachineProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class StatemachineProposalProvider extends AbstractStatemachineProposalProvider {
}
