/**
 * generated by Xtext 2.14.0
 */
package ac.soton.xumlb.scoping;

import ac.soton.xumlb.scoping.AbstractStatemachineScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class StatemachineScopeProvider extends AbstractStatemachineScopeProvider {
}
