/**
 * generated by Xtext 2.14.0
 */
package ac.soton.xumlb.ide;

import ac.soton.xumlb.ide.AbstractStatemachineIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class StatemachineIdeModule extends AbstractStatemachineIdeModule {
}
