/*
 * generated by Xtext 2.21.0
 */
package ac.soton.xumlb.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractStatemachineScopeProvider extends DelegatingScopeProvider {
}
