/**
 * generated by Xtext 2.14.0
 */
package ac.soton.xumlb;

import ac.soton.xumlb.AbstractStatemachineRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class StatemachineRuntimeModule extends AbstractStatemachineRuntimeModule {
}
