/**
 * generated by Xtext 2.14.0
 */
package ac.soton.xumlb.validation;

import ac.soton.eventb.statemachines.Statemachine;
import ac.soton.xumlb.validation.AbstractStatemachineValidator;
import org.eclipse.xtext.validation.Check;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class StatemachineValidator extends AbstractStatemachineValidator {
  public final static String INVALID_NAME = "invalidName";
  
  @Check
  public Object checkGreetingStartsWithCapital(final Statemachine stm) {
    return null;
  }
}
