/**
 * generated by Xtext 2.14.0
 */
package ac.soton.xumlb.tests;

import ac.soton.eventb.statemachines.Statemachine;
import ac.soton.xumlb.tests.StatemachineInjectorProvider;
import com.google.inject.Inject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(StatemachineInjectorProvider.class)
@SuppressWarnings("all")
public class StatemachineParsingTest {
  @Inject
  private ParseHelper<Statemachine> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final Statemachine result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
