/*
 * generated by Xtext 2.14.0
 */
package ac.soton.xumlb


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class StatemachineStandaloneSetup extends StatemachineStandaloneSetupGenerated {

	def static void doSetup() {
		new StatemachineStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
