/*
 * generated by Xtext 2.14.0
 */
package ac.soton.xumlb.validation

import org.eclipse.xtext.validation.Check
import ac.soton.eventb.statemachines.Statemachine

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class StatemachineValidator extends AbstractStatemachineValidator {
	
	public static val INVALID_NAME = 'invalidName'

	@Check
	def checkGreetingStartsWithCapital(Statemachine stm) {
		//System.out.println("Here")
	}
	
}
